repos:
-   repo: https://github.com/python/black
    rev: 24.1.1
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
    - id: ruff
-   repo: local
    hooks:
    -   id: giant_gitlab
        name: giant_gitlab
        entry: python gitlab_maker.py
        language: system
        types: [python]