#!/usr/bin/env python3

import datetime


def main():
    outfile = "gitlab2.py"
    tmpfile = "gitlab2.py.tmp"
    with open(tmpfile, "w") as fw:
        fw.write("#!/usr/bin/env python3\n")
        fw.write("# This file is generated by gitlab_maker.py\n")
        fw.write("# Do not edit this file manually!\n")
        fw.write(
            "# Generated on: {}\n".format(datetime.datetime.now().strftime("%Y-%m-%d"))
        )
        fw.write("\n")
        fw.write("def main():\n")
        fw.write("    pass\n")
        fw.write("\n")
        fw.write('if __name__ == "__main__":\n')
        fw.write("    main()\n")

    # compare the tmpfile with the outfile
    with open(outfile, "r") as fr:
        outfile_content = fr.read()
    with open(tmpfile, "r") as fr:
        tmpfile_content = fr.read()
    if outfile_content != tmpfile_content:
        print("The files are different, updating the outfile")
        with open(outfile, "w") as fw:
            fw.write(tmpfile_content)
    else:
        print("The files are the same")
    # remove the tmpfile
    import os

    os.remove(tmpfile)


# run the gitlab_maker.py script if called from the command line
##############################################################
if __name__ == "__main__":
    # calling the main function
    main()
